### ISSUE TITLE
proj_api.h not made in newer proj versions

### ISSUE THREAD

**Issue by khintz** [harphub/meteogrid#5]
When installing meteogrid it failed due to a missing include file "proj_api.h".
I was installing meteogrid like so:
```
remotes::install_github(
  "harphub/harp",
  configure.args = c(
    meteogrid = "--with-proj=/path/to/proj"
  )
)
```
Checking `/path/to/proj ` proj_api.h was not there. It seems to be related to newer proj version not making this include file (but one called `proj.h`).
After downgrading my proj installation from v. 8.0.1 to v. 6.3.2 (https://proj.org/download.html), `proj_api.h` is made and meteogrid installs succesfully.

**Comment by adeckmyn** [comment]
Yes, proj 8 has dropped the old proj_api.h. My latest development version of meteogrid solves this (it checks and has compile options for both versions), but is not yet on github. I have been too occupied on other topics to test it enough. But I will update the code on harphub soon.

**Comment by adeckmyn** [comment]
I just merged the Rcpp branch which also fixes for the new proj.h interface.
